# Generated by Django 3.1.2 on 2021-09-29 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display', models.CharField(max_length=255, verbose_name='Дисплей')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('camera', models.CharField(max_length=255, verbose_name='Основная камера')),
                ('front_cam', models.CharField(max_length=255, verbose_name='Фронтальная камера')),
                ('accum', models.CharField(max_length=255, verbose_name='Объем батареи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display', models.CharField(max_length=255, verbose_name='Дисплей')),
                ('processor', models.CharField(max_length=255, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('no_charge_time', models.CharField(max_length=255, verbose_name='Время без подзарядки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
